// Initial seed portfolio data for MongoDB and in-memory store

export const initialProfile = {
  name: 'Alex Rivera',
  greeting: "Hi, I'm Alex Rivera",
  titlePrefix: 'Creative Developer Building',
  titleHighlight: 'Digital',
  titleSuffix: 'Experiences',
  tagline: 'I design and build modern, fast, and accessible web applications with clean code, intuitive interfaces, and engaging interactive experiences.',
  bio: 'Lead front-end architect and UI engineer specializing in high-performance React architectures, interactive design systems, and responsive 3D web experiences.',
  email: 'alex.rivera@example.com',
  location: 'San Francisco, CA / Remote',
  status: 'Available for work',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
  resumeUrl: '#resume',
  socialLinks: [
    { platform: 'GitHub', url: 'https://github.com', icon: 'Github', handle: '@alexrivera' },
    { platform: 'LinkedIn', url: 'https://linkedin.com', icon: 'Linkedin', handle: 'in/alexrivera-dev' },
    { platform: 'Twitter / X', url: 'https://x.com', icon: 'Twitter', handle: '@alexrivera_ui' },
    { platform: 'Dribbble', url: 'https://dribbble.com', icon: 'Dribbble', handle: 'alexrivera' },
  ],
};

export const initialProjects = [
  {
    id: 'fintrack',
    title: 'FinTrack Dashboard',
    category: 'Fintech & Analytics',
    tagline: 'Modern financial dashboard with analytics, budgets, and real-time insights.',
    description: 'A comprehensive wealth management platform providing real-time portfolio tracking, budget forecasting, custom metric widgets, and transaction categorization with interactive chart visualizers.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    tags: ['React', 'TypeScript', 'Tailwind CSS', 'Recharts'],
    year: '2024',
    featured: true,
    liveUrl: 'https://example.com/fintrack',
    githubUrl: 'https://github.com/example/fintrack',
    metrics: [
      { label: 'Active Users', value: '45,000+' },
      { label: 'Latency', value: '<80ms' },
      { label: 'Crash Rate', value: '0.01%' },
    ],
    keyFeatures: [
      'Real-time streaming portfolio telemetry & market feeds',
      'Dynamic budget forecasting and expense grouping',
      'Sub-millisecond data aggregation via Web Workers',
      'Adaptive light & dark mode interface with export to PDF',
    ],
  },
  {
    id: 'studysphere',
    title: 'StudySphere',
    category: 'EdTech & Collaboration',
    tagline: 'Collaboration platform for students with real-time chat and resources.',
    description: 'A seamless virtual study lounge featuring peer video rooms, markdown notes synchronization, collaborative whiteboard sessions, and an integrated flashcard knowledge graph.',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
    tags: ['React', 'Node.js', 'Socket.io', 'MongoDB'],
    year: '2024',
    featured: true,
    liveUrl: 'https://example.com/studysphere',
    githubUrl: 'https://github.com/example/studysphere',
    metrics: [
      { label: 'Concurrent Rooms', value: '1,200+' },
      { label: 'Sync Latency', value: '24ms' },
      { label: 'Uptime', value: '99.98%' },
    ],
    keyFeatures: [
      'Low-latency WebSocket multi-user synchronization',
      'Real-time shared markdown document editing with version history',
      'Interactive flashcard study algorithm',
      'Integrated resource repository with smart search',
    ],
  },
  {
    id: 'travelista',
    title: 'Travelista',
    category: 'Travel & Booking',
    tagline: 'Travel booking experience with beautiful UI and smooth interactions.',
    description: 'An immersive travel discovery and itinerary builder featuring fluid spatial animations, interactive map routing, dynamic currency conversion, and instant package reservations.',
    image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1200&q=80',
    tags: ['React', 'Tailwind CSS', 'Framer Motion', 'Mapbox'],
    year: '2024',
    featured: true,
    liveUrl: 'https://example.com/travelista',
    githubUrl: 'https://github.com/example/travelista',
    metrics: [
      { label: 'Bookings Processed', value: '$2.4M' },
      { label: 'Lighthouse Score', value: '98/100' },
      { label: 'Conversion Lift', value: '+34%' },
    ],
    keyFeatures: [
      'Kinetic page transitions and micro-interaction feedback',
      'Multi-currency live exchange calculation engine',
      'Interactive 3D itinerary map with route checkpoints',
      'Instant offline travel pass caching',
    ],
  },
  {
    id: 'devblog',
    title: 'DevBlog Platform',
    category: 'Content Platform',
    tagline: 'Minimal blog platform for developers with syntax highlighting.',
    description: 'A clean, high-performance publishing platform for engineering teams featuring rich code block execution, reader bookmarks, RSS generation, and automated OG image creation.',
    image: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1200&q=80',
    tags: ['React', 'Tailwind CSS', 'MDX', 'TypeScript'],
    year: '2023',
    featured: false,
    liveUrl: 'https://example.com/devblog',
    githubUrl: 'https://github.com/example/devblog',
    metrics: [
      { label: 'Monthly Readers', value: '80,000+' },
      { label: 'Page Load', value: '0.4s' },
    ],
    keyFeatures: [
      'Static-first MDX compilation for ultra-fast reading',
      'Interactive syntax highlighted code sandboxes',
      'Full-text fuzzy search with zero runtime footprint',
    ],
  },
  {
    id: 'taskflow-api',
    title: 'TaskFlow Architecture',
    category: 'Backend Architecture',
    tagline: 'RESTful task management API with authentication & rate-limiting.',
    description: 'A scalable task management service built on Node.js and MongoDB with OAuth 2.0, Redis token caching, multi-tenant workspace isolation, and automated webhooks.',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
    tags: ['Node.js', 'Express', 'MongoDB', 'Redis'],
    year: '2023',
    featured: false,
    liveUrl: 'https://example.com/taskflow',
    githubUrl: 'https://github.com/example/taskflow',
    metrics: [
      { label: 'Requests / Sec', value: '15,000' },
      { label: 'Test Coverage', value: '96%' },
    ],
    keyFeatures: [
      'Role-based access control (RBAC) with scoped tokens',
      'Redis-powered token bucket rate limiting',
      'Automated OpenAPI 3.0 documentation generation',
    ],
  },
];

export const initialSkills = [
  { id: 'ts', name: 'TypeScript', level: 95, category: 'frontend', icon: 'Code', color: 'from-blue-600 to-indigo-600', experience: '5+ years' },
  { id: 'react', name: 'React', level: 92, category: 'frontend', icon: 'Layers', color: 'from-cyan-500 to-blue-500', experience: '5+ years' },
  { id: 'tailwind', name: 'Tailwind CSS', level: 90, category: 'styling', icon: 'Sparkles', color: 'from-teal-400 to-cyan-500', experience: '4+ years' },
  { id: 'node', name: 'Node.js & Express', level: 88, category: 'backend', icon: 'Server', color: 'from-emerald-500 to-green-600', experience: '4+ years' },
  { id: 'mongodb', name: 'MongoDB & Mongoose', level: 85, category: 'database', icon: 'Database', color: 'from-green-600 to-teal-600', experience: '4+ years' },
  { id: 'next', name: 'Next.js', level: 86, category: 'frontend', icon: 'Globe', color: 'from-slate-800 to-slate-600', experience: '3+ years' },
  { id: 'motion', name: 'Framer Motion & Canvas', level: 84, category: 'frontend', icon: 'Sparkles', color: 'from-purple-500 to-pink-500', experience: '3+ years' },
  { id: 'devops', name: 'Docker & CI/CD', level: 78, category: 'devops', icon: 'Cpu', color: 'from-blue-500 to-sky-600', experience: '3+ years' },
];

export const initialExperience = [
  {
    id: 'exp-1',
    role: 'Senior Frontend Architect',
    company: 'TechNova Solutions',
    location: 'Remote',
    type: 'Full-time',
    period: 'Jan 2023 – Present',
    isCurrent: true,
    description: 'Led architecture and migration of core customer-facing SaaS dashboards to React 19 and modern component systems, improving Core Web Vitals by 42% and establishing component design systems across 8 squads.',
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'REST APIs', 'Node.js'],
  },
  {
    id: 'exp-2',
    role: 'Full-Stack Developer',
    company: 'PixelCraft Labs',
    location: 'San Francisco, CA',
    type: 'Full-time',
    period: 'Jul 2021 – Dec 2022',
    isCurrent: false,
    description: 'Engineered high-concurrency client applications, dynamic chart widgets using D3/Recharts, and collaborative canvas interfaces with WebSocket event synchronization and MongoDB persistence.',
    technologies: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
  },
  {
    id: 'exp-3',
    role: 'Web Developer Intern',
    company: 'InnovateX',
    location: 'New York, NY',
    type: 'Internship',
    period: 'Jan 2021 – Jun 2021',
    isCurrent: false,
    description: 'Developed responsive landing pages, automated client onboarding workflows, and reduced bundle size by 35% through tree-shaking and lazy-loading optimizations.',
    technologies: ['JavaScript', 'HTML5/CSS3', 'React', 'Git', 'Webpack'],
  },
];

export const initialServices = [
  {
    id: 'web-dev',
    title: 'Web Development',
    shortDesc: 'Scalable, performant web applications',
    fullDesc: 'Custom enterprise web applications, single-page application architectures, sub-second load times, and performance profiling.',
    icon: 'Code2',
    accentColor: 'from-violet-500/20 to-purple-500/10 text-purple-600',
    tags: ['Custom web apps', 'SPA architecture', 'Performance optimization', 'Web Vitals'],
  },
  {
    id: 'frontend-dev',
    title: 'Frontend Development',
    shortDesc: 'Modern interfaces with clean, efficient code',
    fullDesc: 'State-of-the-art UI architectures built with React, Tailwind CSS, TypeScript, and fluid animations.',
    icon: 'Layout',
    accentColor: 'from-blue-500/20 to-sky-500/10 text-blue-600',
    tags: ['React', 'Tailwind CSS', 'Interactive UI/UX', 'Framer Motion'],
  },
  {
    id: 'backend-dev',
    title: 'Backend Development',
    shortDesc: 'Robust APIs and secure server-side solutions',
    fullDesc: 'High-throughput RESTful APIs, distributed database schemas, caching layers, and secure authentication flows.',
    icon: 'Server',
    accentColor: 'from-cyan-500/20 to-teal-500/10 text-cyan-700',
    tags: ['REST APIs', 'MongoDB & Mongoose', 'Node.js & Express', 'Authentication'],
  },
  {
    id: 'uiux-design',
    title: 'UI/UX & Interactive Design',
    shortDesc: 'Engaging experiences that connect',
    fullDesc: 'Crafting thoughtful design systems, wireframing user journeys, designing tactile micro-interactions, and component libraries.',
    icon: 'PenTool',
    accentColor: 'from-indigo-500/20 to-pink-500/10 text-indigo-600',
    tags: ['Wireframing', 'Design Systems', 'Micro-animations', 'Component Design'],
  },
];
